name: deploy

on:
  workflow_dispatch:
  push:
    tags:        
      - '**'   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: ./mvnw clean install -Dmaven.test.skip
      # run: mvn clean install
    - uses: actions/upload-artifact@master
      with:
        name: build-artifact
        path: ./target/
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: ./target/
      - name: copy file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: ./target/*
          target: /home/rizal/unravel/api
      - name: compose up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            sudo cp -R ~/unravel/api/* /root/my-docker-compose/api-unravel-mlg
            sudo sh -c "cd /root/my-docker-compose/api-unravel-mlg/; docker compose up -d"
